/**
 * Legal document draft generator for LegacyNest
 * All documents are DRAFT TEMPLATES only — not legally binding without lawyer review.
 */

import { jsPDF } from "jspdf";
import type { LegalWill, LegalTrust, LegalGuardianship, LegalPoa } from "./data/mock";

const OG = [224, 123, 42] as const;
const DK = [30, 20, 10] as const;
const MU = [110, 90, 70] as const;
const BOR = [220, 200, 180] as const;
const WH = [255, 255, 255] as const;
const PAGE_W = 210; const PAGE_H = 297; const M = 20; const CW = PAGE_W - M * 2;
const LH = 6;

function rgb(doc: jsPDF, w: "text"|"fill"|"draw", c: readonly [number,number,number]) {
  if (w==="text")  doc.setTextColor(c[0],c[1],c[2]);
  if (w==="fill")  doc.setFillColor(c[0],c[1],c[2]);
  if (w==="draw")  doc.setDrawColor(c[0],c[1],c[2]);
}
function fnt(doc: jsPDF, bold=false, size=10) { doc.setFont("helvetica", bold?"bold":"normal"); doc.setFontSize(size); }
function ctr(): [typeof jsPDF.prototype.text] { return []; } // unused, just text alignment helpers

function pageHeader(doc: jsPDF, title: string, pageN: number) {
  rgb(doc,"fill",OG); doc.rect(0,0,PAGE_W,12,"F");
  fnt(doc,true,9); rgb(doc,"text",WH);
  doc.text("LegacyNest — Legal Planning (DRAFT TEMPLATE)", M, 8);
  doc.text(`Page ${pageN}`, PAGE_W-M, 8, {align:"right"});
  rgb(doc,"text",DK);
}

function disclaimer(doc: jsPDF, y: number): number {
  rgb(doc,"fill",[255,245,235]); doc.rect(M, y, CW, 18,"F");
  rgb(doc,"draw",OG); doc.setLineWidth(0.3); doc.rect(M,y,CW,18,"S");
  fnt(doc,true,8); rgb(doc,"text",[180,80,10]);
  doc.text("IMPORTANT DISCLAIMER", M+3, y+5);
  fnt(doc,false,7.5); rgb(doc,"text",DK);
  const lines = doc.splitTextToSize(
    "This is a draft planning template generated by LegacyNest for informational purposes ONLY. It does NOT constitute a legally binding document and CANNOT be used as such. You MUST consult a qualified lawyer licensed in your jurisdiction before executing any legal document. Laws governing wills, trusts, guardianship and powers of attorney vary by state and require specific formalities (witnesses, notarisation, court orders, registration) to be valid.",
    CW-6
  );
  doc.text(lines, M+3, y+10);
  return y + 22;
}

function section(doc: jsPDF, y: number, title: string): number {
  rgb(doc,"fill",[254,248,240]); doc.rect(M,y,CW,7,"F");
  rgb(doc,"fill",OG); doc.rect(M,y,2.5,7,"F");
  fnt(doc,true,10); rgb(doc,"text",OG);
  doc.text(title, M+5, y+5);
  return y+10;
}

function kv(doc: jsPDF, y: number, label: string, value?: string, indent=0): number {
  const val = value?.trim() || "________________________";
  fnt(doc,true,8.5); rgb(doc,"text",DK);
  doc.text(label+":", M+indent, y);
  fnt(doc,false,8.5); rgb(doc,"text", value?.trim() ? DK : MU);
  const lines = doc.splitTextToSize(val, CW - 48 - indent);
  doc.text(lines, M+48+indent, y);
  return y + Math.max(LH, lines.length * LH);
}

function para(doc: jsPDF, y: number, text: string, indent=0): number {
  fnt(doc,false,8.5); rgb(doc,"text",DK);
  const lines = doc.splitTextToSize(text, CW-indent);
  doc.text(lines, M+indent, y);
  return y + lines.length * LH + 2;
}

function line(doc: jsPDF, y: number): number {
  rgb(doc,"draw",BOR); doc.setLineWidth(0.2);
  doc.line(M,y,PAGE_W-M,y);
  return y+5;
}

function signBlock(doc: jsPDF, y: number, label: string): number {
  if (y + 22 > PAGE_H - 18) { doc.addPage(); pageHeader(doc,"",0); y=20; }
  fnt(doc,false,8.5); rgb(doc,"text",DK);
  doc.text(label, M, y+10);
  rgb(doc,"draw",MU); doc.setLineWidth(0.3);
  doc.line(M,y+18,M+70,y+18);
  doc.text("(Signature)", M, y+22);
  doc.line(M+80,y+18,M+140,y+18);
  doc.text("(Date)", M+80, y+22);
  return y+28;
}

function save(doc: jsPDF, filename: string) {
  // Stamp "Page X of Y" on every page
  const total = doc.getNumberOfPages();
  for (let i=1;i<=total;i++) {
    doc.setPage(i);
    fnt(doc,false,7); rgb(doc,"text",MU);
    doc.text(`Page ${i} of ${total} — DRAFT — LegacyNest Legal Planning Template`, PAGE_W/2, PAGE_H-5, {align:"center"});
  }
  doc.save(filename);
}

// ── DRAFT WILL ───────────────────────────────────────────────────────────────
export function generateDraftWill(
  will: LegalWill,
  parentName: string,
  childName: string,
  todayStr: string
) {
  const doc = new jsPDF({orientation:"portrait",unit:"mm",format:"a4"});
  let y = 18; let pg = 1;
  pageHeader(doc,"Draft Will",pg);

  // Title
  fnt(doc,true,16); rgb(doc,"text",OG);
  doc.text("LAST WILL AND TESTAMENT", PAGE_W/2, y+10, {align:"center"});
  fnt(doc,true,11); rgb(doc,"text",DK);
  doc.text("(DRAFT TEMPLATE — NOT LEGALLY VALID WITHOUT LAWYER REVIEW)", PAGE_W/2, y+17, {align:"center"});
  y += 24;

  y = disclaimer(doc, y);
  y += 3;

  // Preamble
  y = section(doc,y,"1. DECLARATION");
  y = para(doc,y,`I, ${parentName || "________________________"}, residing at ________________________, being of sound mind, memory and understanding, hereby revoke all previous wills and codicils made by me and declare this to be my Last Will and Testament, made this ${todayStr}.`);
  y += 2;

  // Family & Beneficiary
  y = section(doc,y,"2. FAMILY DETAILS");
  y = kv(doc,y,"My full name", parentName);
  y = kv(doc,y,"My child (beneficiary)", childName);
  y = kv(doc,y,"Child's disability", "");
  y += 2;

  // Special Needs Trust
  y = section(doc,y,"3. SPECIAL NEEDS TRUST");
  y = para(doc,y,"I DIRECT that the residue of my estate be held in trust for the benefit of my child " + (childName||"________________________") + ". The trust shall be managed as a Special Needs Trust under the Indian Trusts Act, 1882 and the Rights of Persons with Disabilities Act, 2016, such that my child's eligibility for government disability benefits and schemes (including Niramaya, National Trust schemes and state government schemes) is not impaired.");
  y = kv(doc,y,"Trust name", will.vaultDocumentRef||"");
  y += 2;

  // Executors
  y = section(doc,y,"4. APPOINTMENT OF EXECUTORS");
  y = para(doc,y,"I APPOINT the following person(s) as Executor(s) of this Will:");
  y = kv(doc,y,"Primary Executor", will.primaryExecutorName);
  y = kv(doc,y,"Phone / Email", `${will.primaryExecutorPhone||""} / ${will.primaryExecutorEmail||""}`);
  y += 3;
  y = para(doc,y,"In the event the Primary Executor is unable or unwilling to act, I APPOINT:");
  y = kv(doc,y,"Alternate Executor", will.alternateExecutorName);
  y = kv(doc,y,"Phone / Email", `${will.alternateExecutorPhone||""} / ${will.alternateExecutorEmail||""}`);
  y += 2;

  // Guardian
  y = section(doc,y,"5. GUARDIAN OF CHILD");
  y = para(doc,y,"In the event I am not survived by my spouse, or if my spouse is unable to act as guardian, I appoint ________________________ as the guardian of my child " + (childName||"________________________") + ", with full powers as required under the Guardians and Wards Act, 1890 and the Rights of Persons with Disabilities Act, 2016.");
  y += 2;

  // Assets
  y = section(doc,y,"6. SPECIFIC BEQUESTS");
  y = para(doc,y,"I give, bequeath and devise all my property, both moveable and immoveable, including but not limited to:");
  y = para(doc,y,"• All financial assets (bank accounts, fixed deposits, mutual funds, shares)\n• All immoveable property\n• All insurance policy proceeds\n• All pension and provident fund proceeds",4);
  y = para(doc,y,"...to the Special Needs Trust created for the benefit of " + (childName||"my child") + ".");
  y += 2;

  // Legal advisor
  y = section(doc,y,"7. LEGAL ADVISOR");
  y = kv(doc,y,"Drafting lawyer", will.lawyerName);
  y = kv(doc,y,"Firm", will.lawyerFirm);
  y = kv(doc,y,"Phone", will.lawyerPhone);
  y += 2;

  // Notes
  y = section(doc,y,"8. NOTES");
  if (will.notes) y = para(doc,y,will.notes);
  else y = para(doc,y,"(Add any specific instructions, conditions, or exclusions here)");
  y += 5;

  // Attestation
  if (y + 60 > PAGE_H-20) { doc.addPage(); pg++; pageHeader(doc,"Draft Will",pg); y=20; }
  y = section(doc,y,"9. ATTESTATION");
  y = para(doc,y,"IN WITNESS WHEREOF, I have hereunto subscribed my name this ______ day of _____________, 20___.");
  y += 5;
  y = signBlock(doc,y,"TESTATOR (Maker of Will):");
  y += 5;
  y = para(doc,y,"Signed in the presence of us, both present at the same time, who at the Testator's request, in the Testator's presence and in the presence of each other, have subscribed our names as witnesses:");
  y = signBlock(doc,y,"WITNESS 1 — Name, Address, Occupation:");
  y = signBlock(doc,y,"WITNESS 2 — Name, Address, Occupation:");
  y += 4;
  y = para(doc,y,"NOTE: Under Indian law, a Will must be signed by the Testator and attested by at least 2 witnesses in each other's presence. The witnesses must not be beneficiaries under the Will.");

  save(doc, `LegacyNest_Draft_Will_${(parentName||"").replace(/\s+/g,"_")}.pdf`);
}

// ── DRAFT SPECIAL NEEDS TRUST ────────────────────────────────────────────────
export function generateDraftTrust(
  trust: LegalTrust,
  parentName: string,
  childName: string,
  todayStr: string
) {
  const doc = new jsPDF({orientation:"portrait",unit:"mm",format:"a4"});
  let y = 18; let pg = 1;
  pageHeader(doc,"Draft Special Needs Trust",pg);

  fnt(doc,true,15); rgb(doc,"text",OG);
  doc.text("SPECIAL NEEDS TRUST DEED", PAGE_W/2, y+10, {align:"center"});
  fnt(doc,true,10); rgb(doc,"text",DK);
  doc.text("(DRAFT TEMPLATE — MUST BE REGISTERED WITH SUB-REGISTRAR)", PAGE_W/2, y+17, {align:"center"});
  y += 24;

  y = disclaimer(doc,y); y+=3;

  y = section(doc,y,"1. TRUST DETAILS");
  y = kv(doc,y,"Name of Trust", trust.trustName);
  y = kv(doc,y,"Type", trust.trustType);
  y = kv(doc,y,"Registration No.", trust.registrationNumber);
  y = kv(doc,y,"Registration Date", trust.registrationDate);
  y = kv(doc,y,"Trust PAN", trust.panNumber);
  y += 2;

  y = section(doc,y,"2. PARTIES");
  y = para(doc,y,"SETTLOR (Creator of Trust):");
  y = kv(doc,y,"Name", parentName, 4);
  y += 3;
  y = para(doc,y,"BENEFICIARY:");
  y = kv(doc,y,"Name", childName||trust.beneficiaryName, 4);
  y = para(doc,y,"The Beneficiary is a person with disability as defined under the Rights of Persons with Disabilities Act, 2016.",4);
  y += 2;

  y = section(doc,y,"3. TRUSTEES");
  y = kv(doc,y,"Managing Trustee", trust.managingTrusteeName);
  y = kv(doc,y,"Phone", trust.managingTrusteePhone);
  y += 2;
  y = kv(doc,y,"Co-Trustee", trust.coTrusteeName);
  y = kv(doc,y,"Phone", trust.coTrusteePhone);
  y += 2;
  y = kv(doc,y,"Successor Trustee", trust.successorTrusteeName);
  y = kv(doc,y,"Phone", trust.successorTrusteePhone);
  y += 2;

  y = section(doc,y,"4. TRUST OBJECTIVES");
  y = para(doc,y,"The Trust is created for the following purposes:");
  const objectives = [
    "To provide for the care, comfort, welfare, support, maintenance, education and medical needs of the Beneficiary throughout their lifetime.",
    "To supplement, and not supplant, any government benefits, disability schemes or entitlements available to the Beneficiary, including Niramaya Health Insurance, National Trust schemes, Gharaunda, Samarth, NHFDC loans and state government disability pensions.",
    "To ensure the Beneficiary's assets do not exceed limits that would disqualify them from government benefit schemes.",
    "To provide for residential care, therapeutic support and social participation of the Beneficiary.",
  ];
  objectives.forEach((o,i)=>{ y=para(doc,y,`${i+1}. ${o}`,4); y+=1; });
  y += 2;

  y = section(doc,y,"5. TRUST CORPUS AND FUNDING");
  y = kv(doc,y,"Initial corpus (₹)", trust.annualCorpusTarget ? `₹${trust.annualCorpusTarget.toLocaleString("en-IN")} (annual target)` : "");
  y = para(doc,y,"The Trust shall be funded from the Settlor's estate, life insurance proceeds, gifts from family members, and any other lawful contributions. The Managing Trustee shall invest the corpus prudently as per the Indian Trusts Act, 1882.");
  y += 2;

  y = section(doc,y,"6. TRUSTEE POWERS AND DUTIES");
  const powers = [
    "Invest and manage Trust assets prudently for the benefit of the Beneficiary.",
    "Make distributions for the Beneficiary's care, medical treatment, therapy, education, housing, recreational activities and general welfare.",
    "Maintain proper accounts and file annual returns as required by law.",
    "Apply for and receive government benefits, schemes and concessions on behalf of the Beneficiary.",
    "Purchase immoveable property for residential use of the Beneficiary.",
    "Appoint professional advisors, caregivers and managers as required.",
  ];
  powers.forEach((p,i)=>{ y=para(doc,y,`${i+1}. ${p}`,4); y+=1; });
  y += 2;

  y = section(doc,y,"7. DISTRIBUTION RULES");
  y = para(doc,y,"The Managing Trustee shall make distributions for the Beneficiary's needs as described above, ensuring that no distribution causes the loss of any government benefit. The Trust is a Discretionary Special Needs Trust — no beneficiary has a fixed legal right to any distribution.");
  y += 2;

  y = section(doc,y,"8. TERMINATION");
  y = para(doc,y,"The Trust shall terminate upon the death of the Beneficiary, whereupon the remaining corpus shall be distributed as follows: ________________________ (specify alternate beneficiary or charitable organisation).");
  y += 2;

  if (y+50>PAGE_H-20){ doc.addPage(); pg++; pageHeader(doc,"Draft SNT",pg); y=20; }
  y = section(doc,y,"9. REGISTRATION NOTE");
  y = para(doc,y,"This Trust Deed MUST be executed on non-judicial stamp paper of adequate value and registered with the Sub-Registrar of Assurances having jurisdiction. The Trust must also obtain a PAN card and may need registration under the Foreign Contribution Regulation Act if receiving foreign donations.");
  y += 3;

  y = section(doc,y,"10. EXECUTION");
  y = signBlock(doc,y,"SETTLOR:");
  y = signBlock(doc,y,"MANAGING TRUSTEE:");
  y = signBlock(doc,y,"CO-TRUSTEE:");
  y = signBlock(doc,y,"WITNESS 1:");
  y = signBlock(doc,y,"WITNESS 2:");

  save(doc, `LegacyNest_Draft_SNT_${(trust.trustName||"Trust").replace(/\s+/g,"_")}.pdf`);
}

// ── DRAFT POWER OF ATTORNEY ───────────────────────────────────────────────────
export function generateDraftPoa(
  poa: LegalPoa,
  parentName: string,
  childName: string,
  todayStr: string
) {
  const doc = new jsPDF({orientation:"portrait",unit:"mm",format:"a4"});
  let y = 18; let pg = 1;
  pageHeader(doc,"Draft Power of Attorney",pg);

  fnt(doc,true,15); rgb(doc,"text",OG);
  doc.text("POWER OF ATTORNEY", PAGE_W/2, y+10, {align:"center"});
  fnt(doc,true,10); rgb(doc,"text",DK);
  const scopeLabel = poa.poaScope ? `(${poa.poaScope.toUpperCase()} POWER OF ATTORNEY)` : "(GENERAL / FINANCIAL POWER OF ATTORNEY)";
  doc.text(scopeLabel, PAGE_W/2, y+17, {align:"center"});
  y += 24;

  y = disclaimer(doc,y); y+=3;

  y = section(doc,y,"1. PARTIES");
  y = para(doc,y,"I, the DONOR:");
  y = kv(doc,y,"Name", parentName, 4);
  y = para(doc,y,"(hereinafter called 'the Donor') do hereby appoint:");
  y = kv(doc,y,"Attorney / Donee", poa.holderName, 4);
  y = kv(doc,y,"Phone", poa.holderPhone, 4);
  y = para(doc,y,"(hereinafter called 'the Attorney') as my true and lawful attorney.");
  y += 2;

  y = section(doc,y,"2. SCOPE OF AUTHORITY");
  const scopePowers: Record<string, string[]> = {
    "Financial": [
      "Operate all bank accounts, fixed deposits, demat accounts, mutual fund accounts and other financial instruments in my name.",
      "Receive, collect and give valid receipts for all amounts due to me.",
      "Execute and register sale deeds, lease deeds, gift deeds and other property documents.",
      "Deal with income tax, GST, and other tax authorities on my behalf.",
      "Manage, sell, purchase and deal with all my moveable and immoveable properties.",
      `Manage all financial affairs related to the care and welfare of my child ${childName||"________________________"}.`,
    ],
    "Medical": [
      `Make all medical decisions for my child ${childName||"________________________"}, including consent for medical procedures, surgeries and treatments.`,
      "Access all medical records and communicate with healthcare providers.",
      "Arrange for hospitalisation, therapy, and medical care.",
      "Apply for medical insurance claims and government health schemes on behalf of my child.",
    ],
    "General": [
      "All powers under Financial and Medical categories above.",
      "Sign and execute all documents, agreements and contracts on my behalf.",
      "Appear before all courts, tribunals, government departments and authorities.",
      "Do all acts and things as fully and effectually as I could do personally.",
    ],
    "Limited": [
      "________________________ (specify the limited powers granted)",
      "This Power of Attorney is strictly limited to the above purposes and does not confer any other authority.",
    ],
  };
  const powers = scopePowers[poa.poaScope||"General"] || scopePowers["General"];
  y = para(doc,y,"The Attorney is authorised to:");
  powers.forEach((p,i)=>{ y=para(doc,y,`${i+1}. ${p}`,4); y+=1; });
  y += 2;

  y = section(doc,y,"3. DURATION AND REVOCATION");
  y = kv(doc,y,"Execution Date", poa.executionDate);
  y = kv(doc,y,"Expiry Date", poa.expiryDate || "Until revoked in writing");
  y = para(doc,y,"This Power of Attorney shall remain in force until revoked by me in writing or until the expiry date specified above, whichever is earlier. Any third party who has acted in good faith on this POA before receiving notice of revocation shall not be affected.");
  y += 2;

  y = section(doc,y,"4. CONSIDERATION");
  y = para(doc,y,"This Power of Attorney is given for good and valuable consideration, including the care and welfare of " + (childName||"my child") + ", receipt whereof is hereby acknowledged.");
  y += 2;

  if (y+40>PAGE_H-20){ doc.addPage(); pg++; pageHeader(doc,"Draft POA",pg); y=20; }
  y = section(doc,y,"5. EXECUTION");
  y = para(doc,y,`IN WITNESS WHEREOF, I have signed this Power of Attorney on this ${todayStr}.`);
  y += 5;
  y = signBlock(doc,y,"DONOR:");
  y = signBlock(doc,y,"ATTORNEY (Acceptance):");
  y = signBlock(doc,y,"WITNESS 1:");
  y = signBlock(doc,y,"WITNESS 2:");
  y += 3;
  y = para(doc,y,"NOTE: A Power of Attorney for immoveable property must be registered. For medical decisions regarding a child with disability, a court order under the RPWD Act 2016 may provide stronger legal authority than a POA.");

  save(doc, `LegacyNest_Draft_POA_${(poa.holderName||"Attorney").replace(/\s+/g,"_")}.pdf`);
}
