/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as EmergencyConfirmRouteImport } from './routes/emergency-confirm'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminEmergencyRouteImport } from './routes/admin.emergency'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AcceptTokenRouteImport } from './routes/accept.$token'
import { Route as AppVaultRouteImport } from './routes/_app.vault'
import { Route as AppSuccessionRouteImport } from './routes/_app.succession'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResidentialRouteImport } from './routes/_app.residential'
import { Route as AppParentProfileRouteImport } from './routes/_app.parent-profile'
import { Route as AppMedicalRouteImport } from './routes/_app.medical'
import { Route as AppLegalRouteImport } from './routes/_app.legal'
import { Route as AppInsurancePoliciesRouteImport } from './routes/_app.insurance-policies'
import { Route as AppFinancialRouteImport } from './routes/_app.financial'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppEmergencyRouteImport } from './routes/_app.emergency'
import { Route as AppDisabilityDocumentsRouteImport } from './routes/_app.disability-documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChildProfileRouteImport } from './routes/_app.child-profile'
import { Route as AppCaregiverRouteImport } from './routes/_app.caregiver'
import { Route as AppCareCircleRouteImport } from './routes/_app.care-circle'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'
import { Route as AppActionPlanRouteImport } from './routes/_app.action-plan'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyConfirmRoute = EmergencyConfirmRouteImport.update({
  id: '/emergency-confirm',
  path: '/emergency-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmergencyRoute = AdminEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AcceptTokenRoute = AcceptTokenRouteImport.update({
  id: '/accept/$token',
  path: '/accept/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppSuccessionRoute = AppSuccessionRouteImport.update({
  id: '/succession',
  path: '/succession',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentialRoute = AppResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => AppRoute,
} as any)
const AppParentProfileRoute = AppParentProfileRouteImport.update({
  id: '/parent-profile',
  path: '/parent-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalRoute = AppMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalRoute = AppLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppInsurancePoliciesRoute = AppInsurancePoliciesRouteImport.update({
  id: '/insurance-policies',
  path: '/insurance-policies',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialRoute = AppFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppDisabilityDocumentsRoute = AppDisabilityDocumentsRouteImport.update({
  id: '/disability-documents',
  path: '/disability-documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChildProfileRoute = AppChildProfileRouteImport.update({
  id: '/child-profile',
  path: '/child-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppCaregiverRoute = AppCaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => AppRoute,
} as any)
const AppCareCircleRoute = AppCareCircleRouteImport.update({
  id: '/care-circle',
  path: '/care-circle',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppActionPlanRoute = AppActionPlanRouteImport.update({
  id: '/action-plan',
  path: '/action-plan',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/emergency-confirm': typeof EmergencyConfirmRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/sign-in': typeof SignInRoute
  '/support': typeof SupportRoute
  '/action-plan': typeof AppActionPlanRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/care-circle': typeof AppCareCircleRoute
  '/caregiver': typeof AppCaregiverRoute
  '/child-profile': typeof AppChildProfileRoute
  '/dashboard': typeof AppDashboardRoute
  '/disability-documents': typeof AppDisabilityDocumentsRoute
  '/emergency': typeof AppEmergencyRoute
  '/feedback': typeof AppFeedbackRoute
  '/financial': typeof AppFinancialRoute
  '/insurance-policies': typeof AppInsurancePoliciesRoute
  '/legal': typeof AppLegalRoute
  '/medical': typeof AppMedicalRoute
  '/parent-profile': typeof AppParentProfileRoute
  '/residential': typeof AppResidentialRoute
  '/settings': typeof AppSettingsRoute
  '/succession': typeof AppSuccessionRoute
  '/vault': typeof AppVaultRoute
  '/accept/$token': typeof AcceptTokenRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/emergency-confirm': typeof EmergencyConfirmRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/sign-in': typeof SignInRoute
  '/support': typeof SupportRoute
  '/action-plan': typeof AppActionPlanRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/care-circle': typeof AppCareCircleRoute
  '/caregiver': typeof AppCaregiverRoute
  '/child-profile': typeof AppChildProfileRoute
  '/dashboard': typeof AppDashboardRoute
  '/disability-documents': typeof AppDisabilityDocumentsRoute
  '/emergency': typeof AppEmergencyRoute
  '/feedback': typeof AppFeedbackRoute
  '/financial': typeof AppFinancialRoute
  '/insurance-policies': typeof AppInsurancePoliciesRoute
  '/legal': typeof AppLegalRoute
  '/medical': typeof AppMedicalRoute
  '/parent-profile': typeof AppParentProfileRoute
  '/residential': typeof AppResidentialRoute
  '/settings': typeof AppSettingsRoute
  '/succession': typeof AppSuccessionRoute
  '/vault': typeof AppVaultRoute
  '/accept/$token': typeof AcceptTokenRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/emergency-confirm': typeof EmergencyConfirmRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/sign-in': typeof SignInRoute
  '/support': typeof SupportRoute
  '/_app/action-plan': typeof AppActionPlanRoute
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/care-circle': typeof AppCareCircleRoute
  '/_app/caregiver': typeof AppCaregiverRoute
  '/_app/child-profile': typeof AppChildProfileRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/disability-documents': typeof AppDisabilityDocumentsRoute
  '/_app/emergency': typeof AppEmergencyRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/financial': typeof AppFinancialRoute
  '/_app/insurance-policies': typeof AppInsurancePoliciesRoute
  '/_app/legal': typeof AppLegalRoute
  '/_app/medical': typeof AppMedicalRoute
  '/_app/parent-profile': typeof AppParentProfileRoute
  '/_app/residential': typeof AppResidentialRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/succession': typeof AppSuccessionRoute
  '/_app/vault': typeof AppVaultRoute
  '/accept/$token': typeof AcceptTokenRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/emergency-confirm'
    | '/reset-password'
    | '/review'
    | '/sign-in'
    | '/support'
    | '/action-plan'
    | '/ai-assistant'
    | '/care-circle'
    | '/caregiver'
    | '/child-profile'
    | '/dashboard'
    | '/disability-documents'
    | '/emergency'
    | '/feedback'
    | '/financial'
    | '/insurance-policies'
    | '/legal'
    | '/medical'
    | '/parent-profile'
    | '/residential'
    | '/settings'
    | '/succession'
    | '/vault'
    | '/accept/$token'
    | '/admin/dashboard'
    | '/admin/emergency'
    | '/admin/feedback'
    | '/admin/support'
    | '/admin/users'
    | '/auth/confirm'
    | '/c/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/emergency-confirm'
    | '/reset-password'
    | '/review'
    | '/sign-in'
    | '/support'
    | '/action-plan'
    | '/ai-assistant'
    | '/care-circle'
    | '/caregiver'
    | '/child-profile'
    | '/dashboard'
    | '/disability-documents'
    | '/emergency'
    | '/feedback'
    | '/financial'
    | '/insurance-policies'
    | '/legal'
    | '/medical'
    | '/parent-profile'
    | '/residential'
    | '/settings'
    | '/succession'
    | '/vault'
    | '/accept/$token'
    | '/admin/dashboard'
    | '/admin/emergency'
    | '/admin/feedback'
    | '/admin/support'
    | '/admin/users'
    | '/auth/confirm'
    | '/c/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/emergency-confirm'
    | '/reset-password'
    | '/review'
    | '/sign-in'
    | '/support'
    | '/_app/action-plan'
    | '/_app/ai-assistant'
    | '/_app/care-circle'
    | '/_app/caregiver'
    | '/_app/child-profile'
    | '/_app/dashboard'
    | '/_app/disability-documents'
    | '/_app/emergency'
    | '/_app/feedback'
    | '/_app/financial'
    | '/_app/insurance-policies'
    | '/_app/legal'
    | '/_app/medical'
    | '/_app/parent-profile'
    | '/_app/residential'
    | '/_app/settings'
    | '/_app/succession'
    | '/_app/vault'
    | '/accept/$token'
    | '/admin/dashboard'
    | '/admin/emergency'
    | '/admin/feedback'
    | '/admin/support'
    | '/admin/users'
    | '/auth/confirm'
    | '/c/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  EmergencyConfirmRoute: typeof EmergencyConfirmRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRoute
  SignInRoute: typeof SignInRoute
  SupportRoute: typeof SupportRoute
  AcceptTokenRoute: typeof AcceptTokenRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  CTokenRoute: typeof CTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-confirm': {
      id: '/emergency-confirm'
      path: '/emergency-confirm'
      fullPath: '/emergency-confirm'
      preLoaderRoute: typeof EmergencyConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emergency': {
      id: '/admin/emergency'
      path: '/emergency'
      fullPath: '/admin/emergency'
      preLoaderRoute: typeof AdminEmergencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accept/$token': {
      id: '/accept/$token'
      path: '/accept/$token'
      fullPath: '/accept/$token'
      preLoaderRoute: typeof AcceptTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/succession': {
      id: '/_app/succession'
      path: '/succession'
      fullPath: '/succession'
      preLoaderRoute: typeof AppSuccessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/residential': {
      id: '/_app/residential'
      path: '/residential'
      fullPath: '/residential'
      preLoaderRoute: typeof AppResidentialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent-profile': {
      id: '/_app/parent-profile'
      path: '/parent-profile'
      fullPath: '/parent-profile'
      preLoaderRoute: typeof AppParentProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical': {
      id: '/_app/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof AppMedicalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal': {
      id: '/_app/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof AppLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insurance-policies': {
      id: '/_app/insurance-policies'
      path: '/insurance-policies'
      fullPath: '/insurance-policies'
      preLoaderRoute: typeof AppInsurancePoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financial': {
      id: '/_app/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof AppFinancialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emergency': {
      id: '/_app/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disability-documents': {
      id: '/_app/disability-documents'
      path: '/disability-documents'
      fullPath: '/disability-documents'
      preLoaderRoute: typeof AppDisabilityDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/child-profile': {
      id: '/_app/child-profile'
      path: '/child-profile'
      fullPath: '/child-profile'
      preLoaderRoute: typeof AppChildProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caregiver': {
      id: '/_app/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof AppCaregiverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/care-circle': {
      id: '/_app/care-circle'
      path: '/care-circle'
      fullPath: '/care-circle'
      preLoaderRoute: typeof AppCareCircleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/action-plan': {
      id: '/_app/action-plan'
      path: '/action-plan'
      fullPath: '/action-plan'
      preLoaderRoute: typeof AppActionPlanRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionPlanRoute: typeof AppActionPlanRoute
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppCareCircleRoute: typeof AppCareCircleRoute
  AppCaregiverRoute: typeof AppCaregiverRoute
  AppChildProfileRoute: typeof AppChildProfileRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDisabilityDocumentsRoute: typeof AppDisabilityDocumentsRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppFinancialRoute: typeof AppFinancialRoute
  AppInsurancePoliciesRoute: typeof AppInsurancePoliciesRoute
  AppLegalRoute: typeof AppLegalRoute
  AppMedicalRoute: typeof AppMedicalRoute
  AppParentProfileRoute: typeof AppParentProfileRoute
  AppResidentialRoute: typeof AppResidentialRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuccessionRoute: typeof AppSuccessionRoute
  AppVaultRoute: typeof AppVaultRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionPlanRoute: AppActionPlanRoute,
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppCareCircleRoute: AppCareCircleRoute,
  AppCaregiverRoute: AppCaregiverRoute,
  AppChildProfileRoute: AppChildProfileRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDisabilityDocumentsRoute: AppDisabilityDocumentsRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppFinancialRoute: AppFinancialRoute,
  AppInsurancePoliciesRoute: AppInsurancePoliciesRoute,
  AppLegalRoute: AppLegalRoute,
  AppMedicalRoute: AppMedicalRoute,
  AppParentProfileRoute: AppParentProfileRoute,
  AppResidentialRoute: AppResidentialRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuccessionRoute: AppSuccessionRoute,
  AppVaultRoute: AppVaultRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmergencyRoute: typeof AdminEmergencyRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmergencyRoute: AdminEmergencyRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  EmergencyConfirmRoute: EmergencyConfirmRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRoute,
  SignInRoute: SignInRoute,
  SupportRoute: SupportRoute,
  AcceptTokenRoute: AcceptTokenRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  CTokenRoute: CTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
